- ovsnl/client.go
- ovsnl/datapath.go
- ovsnl/datapath_linux_test.go
I realized that the `Datapath.List` query was only working coincidentally because a `uint32` and an `ovsh.Header` occupy the same size in memory.  This is the correct version, although it is functionally equivalent.
> ovsnl: add ovsh.Header byte functions, correct Datapath.List data

- ovsdb/client.go
- ovsdb/client_test.go
- ovsdb/internal/jsonrpc/conn.go
- ovsdb/internal/jsonrpc/conn_test.go
- ovsdb/internal/jsonrpc/doc.go
- ovsdb/internal/jsonrpc/testconn.go
Builds a small, internal, JSON-RPC 1.0 implementation, because:
- stdlib can't send some commands to ovsdb-server with proper parameters because it sends nested arrays instead of an array of interfaces
- stdlib can't do RPCs from server to client, as needed for monitor calls
Second commit will replace existing code with this.
> ovsdb/internal/jsonrpc: initial commit

- .travis.yml
- ovsdb/client.go
- ovsdb/client_integration_test.go
- ovsdb/client_test.go
- ovsdb/internal/jsonrpc/conn.go
- ovsdb/internal/jsonrpc/conn_test.go
- ovsdb/internal/jsonrpc/testconn.go
- Sets up `jsonrpc` so that we can do callbacks in `ovsdb.Client` for RPC responses and notifications pushed from the server.
- Sets up a receive loop in `ovsdb` and uses it for standard RPCs.
- Adds a lot of tests to ensure that no race conditions or improper shutdowns occur.
>  ovsdb: add internal receive loop for notifications and callbacks

- ovsdb/client.go
- ovsdb/client_test.go
In a real world scenario, it's totally possible that our client could receive some request that it can't handle, causing it to crash.  Let's just no-op these.
> ovsdb: don't crash on unhandled callback RPC

- ovsdb/client.go
- ovsdb/client_test.go
Could be used as a basis for future metrics and such.
The test shows that the callback leak is now fixed.  I didn't add a new method because it seemed easy enough to do it all in the rpc method.  If I had made a new one, I would have had to release the callback mutex in doCallback, and then re-acquire it to delete the finished callback, which seems inherently race condition prone.
>  ovsdb: add ClientStats, fix callback leak

- ovsdb/client.go
- ovsdb/client_test.go
- ovsdb/internal/jsonrpc/conn.go
- ovsdb/internal/jsonrpc/conn_test.go
- ovsdb/rpc_test.go
ovsdb-server sends some string IDs our way if we talk to it over TCP:
```
[zsh|matt@nerr-2]:~ 0 % telnet localhost 6632   
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"method":"echo","id":"echo","params":[]}Connection closed by foreign host.
```
This prepares us for dealing with those in the receive loop.
> ovsdb: change IDs to strings in preparation for echo replies

- ovsdb/client.go
Weird corner case.  Better safe than sorry, so move them all up top.
> ovsdb: align atomics properly in Client

- ovsdb/client.go
Just so there's some clarity on why methods accept a context.  We don't have any of the "advanced use case" ones yet (like locks, database update notifications), but we will!
> ovsdb: add context documentation for Client

- ovsdb/client.go
- ovsdb/internal/jsonrpc/conn.go
- ovsdb/rpc.go
- ovsdb/rpc_test.go
Some RPCs use really weird requests, e.g.
```
write: {"id":"1","method":"transact","params":["Open_vSwitch",{"op":"select","table":"Bridge","where":[["name","==","ovsbr0"]]}]}
read: {"id":"1","result":[{"rows":[{"name":"ovsbr0","flood_vlans":["set",[]],"netflow":["set",[]],"mirrors":["set",[]],"_uuid":["uuid","4bd512ea-5c3b-488d-b4dc-305f38911210"],"status":["map",[]],"datapath_id":"0000ea12d54b8d48","controller":["set",[]],"_version":["uuid","4ff1a3db-83eb-4df3-a8cb-2366d4a85af0"],"ipfix":["set",[]],"protocols":["set",[]],"fail_mode":["set",[]],"ports":["uuid","003fd088-02b9-406f-9894-19ec15d4da13"],"flow_tables":["map",[]],"other_config":["map",[]],"datapath_type":"","sflow":["set",[
read: ]],"external_ids":["map",[]],"stp_enable":false}]}],"error":null}
```
We need the flexibility of …
> ovsdb: make params an interface for more type flexibility

- ovs/action.go
- ovs/action_test.go
- ovs/actionparser.go
- ovs/actionparser_test.go
Hit another parsing thing -- if we only specify port, OVS is going to give us: `resubmit:4` as the action.  This allows us to take both table/port resubmits (ex `resubmit(1,2)`) and port only resubmits.
> ovs: correctly parse port only resubmit

- ovs/action.go
- ovs/action_test.go
- ovs/actionparser.go
- ovs/actionparser_test.go
Okay!
So, the problem here is that we are treating 0 as a special case for resubmit, when in fact 0 is a valid value for both tables and ports.  To start us off, this introduces ResubmitPort, to match and generate resubmits that look like `resubmit:123`.
We'll need to come back address resubmit to become ResubmitPortTable, but that's going to be a more involved change to make.
@mdlayher @keinohguchi
> ovs: Introduce separate action for ResubmitPort

- ovs/action.go
- ovs/action_test.go
To enable us to use ports for Openflow 1.1+.  This lib needs to be made more version aware down the line.
> ovs: update max openflow port past 1.0 standards

- ovs/openflow.go
- ovs/openflow_test.go
We were attempting to parse this line, causing DumpFlows to mysteriously fail given a bridge with more that X flows configured.
> ovs: do not attempt to parse NXST_FLOW in DumpFlows

- ovs/action.go
- ovs/action_test.go
- ovs/actionparser.go
- ovs/actionparser_test.go
- ovs/match.go
- ovs/match_test.go
- ovs/matchparser.go
- ovs/matchparser_test.go
Allows us access to the conjunction matches and actions inside of OVS.  This allows us to discretely match on dimensions instead of needed a flow for each possible combination of dimensions.
See "Conjunction match fields" in:
http://www.openvswitch.org/support/dist-docs/ovs-fields.7.txt
> ovs: add conj_id matcher

- ovs/client.go
- ovs/client_test.go
- ovs/vswitch.go
- ovs/vswitch_test.go
Add the ovs-ofctl set-controller command which is used to set the ovn controller
address. ovs-ofctl can use this address to communicate with ovs.
Also add SetSSLParam which is used to se the necessary SSL parameters like keys and certs.
> go-openvswitch: add set-controller and SetSSLParam function

- AUTHORS
- ovs/flow_test.go
- ovs/matchflow_test.go
- ovs/matchparser.go
- ovs/matchparser_test.go
Parsing of a flow with tp_dst and tp_src in port/mask format does not work.
Currently parseIntMatch() assumes only a single port in tp_dst and tp_src and not a port-range. As a result parsing a flow with port range fails.
This fix adds logic to parse tp_dst and tp_src in port-range format in a flow.
tp_dst=0xea60/0xffe0
> Handle port range parsing for tp_dst and tp_src keys

- ovs/vswitch.go
- ovs/vswitch_test.go
Applications use this to get the current controller address set in ovs.
this is needed if user wants to verify if the ovs has the address currently
support, if not user can overwrite it with the supported one.
Also add the unit test.
> add get-controller which is used to get the current controller address

- ovsnl/internal/ovsh/const.go
We aren't using any of this but it can't hurt to bring it up to date.
> ovsnl/internal/ovsh: regenerate constants and types

- ovs/client.go
- ovs/client_test.go
Support the TCP connection method for OVSDB and it should be applied to all ovs commands.
> Support the TCP connection for OVSDB

- ovs/vswitch.go
- ovs/vswitch_test.go
Looks like `strings.Split` will let VSwitch.ListBridges()  result to []string{""} not []string{} 
if `ovs-vsctl list-br` output string is empty: "".
> Check if list bridge output is empty

- ovs/match.go
- ovs/matchparser.go
- ovs/matchparser_test.go
- ovsnl/datapath.go
Updated ICMPv6 code and type to ovs match so that ovs-appctl ofproto/trace can support icmpv6.
Fix for Travis-CI build. Removed HeaderFlags prefix based on netlink's recent change:
https://github.com/mdlayher/netlink/commit/080e8e36878e0f73c5a28fb285527eefe3603390#diff-b95c50d14ed7b4bb1cfecdc4e498d4dcL64
> Added ICMPv6 code and type to OVS match

- ovs/proto_trace.go
- ovs/proto_trace_test.go
LOCAL is equivalent to 65534 according to OVS docs [1].
[1] https://www.mankier.com/7/ovs-fields#Metadata_Fields
> Parse the special LOCAL port correctly in ofproto/trace flows

- ovs/match.go
- ovs/match_test.go
I confirmed that this syntax is supported locally.
```
root@s2r3node2:/home/mbenami# ovs-ofctl --version
ovs-ofctl (Open vSwitch) 2.7.3
OpenFlow versions 0x1:0x4
root@s2r3node2:/home/mbenami# ovs-ofctl dump-flows mzb | grep metadata
cookie=0x0, duration=2209.774s, table=0, n_packets=0, n_bytes=0, idle_age=2209, priority=800,arp,metadata=0x12 actions=group:809
```
uint64 data type selected in reference to REGISTER FIELDS section of this document
http://www.openvswitch.org/support/dist-docs/ovs-fields.7.txt
> add metadata match

- ovs/app.go
- ovs/proto_trace.go
It can help to know the precise ovs-appctl command to run so that it
can be run manually.
> Save ovs-appctl command for reference by callers

- ovs/match.go
- ovs/match_test.go
This match can be used inside of a learn action.
```
field=value
Specifies that field, in the new  flow,  must  match  the
literal  value,  e.g. dl_type=0x800. Shorthand match syn‐
tax, such as ip in place of dl_type=0x800,  is  not  sup‐
ported.
field=src
Specifies that field in the new flow must match src taken
from the packet currently being processed.  For  example,
udp_dst=udp_src, applied to a UDP packet with source port
53, creates a flow which matches  udp_dst=53.  field  and
src must have the same width.
```
from "learn action" section in ovs-actions man page: http://www.openvswitch.org/support/dist-docs/ovs-actions.7.txt
> add FieldMatch

- ovs/action.go
- ovs/action_test.go
```
The move action
Syntax:
move:src->dst
Copies the named bits from field or subfield src to field  or  subfield
dst. src and dst should fields or subfields in the syntax described un‐
der ``Field Specifications’’ above. The two fields  or  subfields  must
have the same width.
```
From http://www.openvswitch.org/support/dist-docs/ovs-actions.7.txt
> add Move action

- ovs/action.go
- ovs/action_test.go
```
output:field
Adds an output action to the new flow’s actions that out‐
puts to the OpenFlow port taken from field, which must be
a field as described above.
```
The output:field syntax can be used both in normal `output` actions, as well as in an action inside a `learn` action. 
When used inside the `learn` action the `output:field` syntax is the only acceptable form.
http://www.openvswitch.org/support/dist-docs/ovs-actions.7.txt
> add output:field action

- ovsnl/client.go
- ovsnl/client_linux_test.go
Quick PR to get master green again.  It appears this netlink family is being returned now in integration tests, where it wasn't previously.  Meant to unblock @btsomogyi
> ovsnl: add awareness for ovs_meter

- .travis.yml
- ovs/app.go
- ovs/matchparser.go
- ovs/matchparser_test.go
- ovs/proto_trace.go
- ovs/proto_trace_test.go
When tracing a packet that goes through the connection tracker,
--ct-next can be specified to set the states expected.
Update parseCTState() with updated format.
Change the parser to extract the protocol in a more flexible way.
Change the parser to skip unused keywords.
> Update the ProtoTrace function to accept extra parameters.

- ovsnl/client.go
- ovsnl/client_linux_test.go
Before this commit the ovnl client logic was such that it needs to be
kept in lock-step synchronization with a particular version of the
netlink interface. This is too fragile, as each new update requires
touching this logic, which in turn makes it non-backward compatible.
This commit flips the logic on its head and instead makes the client
complains only if no 'known' families are found. This makes the init
logic future proof and backward compatible.
> ovsnl: only fail if no known families are found

- ovs/vswitch.go
- ovs/vswitch_test.go
This allows us to alter the MTU of interfaces managed by OVS beyond their default values.
> ovs: allow for MTU configuration of interfaces

- ovs/actionparser.go
- ovs/actionparser_test.go
The `move` action was implemented in this library:
https://github.com/digitalocean/go-openvswitch/blob/master/ovs/action.go#L622-L648
However, we're missing a companion parser for this action to allow flows with this action to be properly read.  This PR adds that to allow them to be properly read.
> ovs: add action parser for move

- ovs/app.go
- ovs/proto_trace.go
The output isn't very large and it is useful to save it for verbose
output when callers want to inspect it as a whole.
> save output of ofproto/trace

- AUTHORS
- ovs/match.go
- ovs/match_test.go
- ovs/matchparser.go
- ovs/matchparser_test.go
Fixes #118.
This pull request adds types/functions which allow the matching of UDP source/destination ports. I basically just duplicated everything related to TCP and created UDP-specific variants.
The one thing which I did _not_ duplicate was this interface:
```go
// A TransportPortRanger represents a port range that can be expressed as an array of bitwise matches.
type TransportPortRanger interface {
MaskedPorts() ([]Match, error)
}
```
I'm not sure if it makes sense to have both TCP and UDP port ranges match the same interface; if it doesn't make sense, then I'd be happy to create a `type UdpPortRanger interface { MaskedUdpPorts() ([]Match, error) }` to separate these.
I'm definitely looking for feedback on that matter.
> Add ability to match UDP source/destination ports

- .github/workflows/go.yml
- ovs/match.go
The InPortMatch is using a %q for an int. Should be using a %d
Had to update the go.yml, it was attempting to install the latest version of staticcheck which was expecting go v1.19. This was causing failures during test run.
> Update InPortMatch GoString format

- ovs/matchflow.go
- ovs/matchflow_test.go
- ovs/openflow.go
- ovs/openflow_test.go
1. Fixed a issue to match zeo ovscookie
2. Added a method to dump flow using a flow filter
> Added a method to dump flows matching a flow

- AUTHORS
- ovs/flow.go
- ovs/flow_test.go
- ovs/openflow.go
- ovs/openflow_test.go
Implement stats fetch using dump-flows to provide an option to get statistics for all matching flows in one shot.
Also, provide an option to report interface names instead of port numbers, if requested.
This was also requested in https://github.com/digitalocean/go-openvswitch/issues/128
> Implement stats fetch using dump-flows 
